
title: "HomeRun - Cut the busy work"
email: "hello@homerun-gmbh.de"
description:  "HomeRun - Entwickelt digitale Assistenzen im Bereich Immobilienverwaltung"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.homerun-gmbh.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
sass:
  sass_dir: _sass
  style: compressed
include:
  - '_pages'
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
navigation:
  - title: Home
    url: /
