
title: "HomeRun - Cut the busy work"
email: "hello@homerun-gmbh.de"
description:  "HomeRun -Entwicklt AI gestütze Assistenten im Bereich Immobilienverwaltung"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://homerun-gmbh.github.io/website" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
sass:
  sass_dir: _sass
  style: compressed
include:
  - '_pages'
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
navigation:
  - title: Home
    url: /

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
